/**
 * COHERENT-DESIGN.md serializer. LLM-agnostic per codex consult Q7 —
 * consumes LabeledCluster[] regardless of source (llm/deterministic/cache/
 * human). The DRAFT header is non-negotiable: this file is auto-generated
 * input for human review, never canonical. See PLAN.md §162 + codex #20.
 */

import type { ScanRunMetadata } from '../json-output.js'
import { pickSamples } from './samples.js'
import type { LabeledCluster } from './types.js'

const DRAFT_BANNER = [
  '> **DRAFT — auto-generated from code. Not canonical until reviewed.**',
  '>',
  '> Generated by `coherent scan`. Move accepted clusters into your',
  '> project DESIGN.md after human review. Re-running this scan will',
  '> overwrite this file but cluster IDs are stable across runs.',
].join('\n')

const KIND_HEADERS: Record<string, string> = {
  raw_button_tag: 'Raw `<button>` elements',
  include_partial: 'Blade partial includes',
  x_component_usage: 'Blade `<x-*>` components',
  at_class_directive: '`@class([...])` directives',
  conditional_class_array: 'Conditional class arrays',
  inline_classes: 'Inline class bags',
}

export interface SerializeOptions {
  metadata: ScanRunMetadata
  samplesPerCluster?: number
}

function formatSampleLine(file: string, line: number): string {
  return `\`${file}:${line}\``
}

function formatCluster(labeled: LabeledCluster, samplesPerCluster: number): string {
  const { cluster, human_label, suggested_role, confidence, source } = labeled
  const memberCount = cluster.members.length
  const samples = pickSamples(cluster.members, samplesPerCluster)
  const tokenPreview = cluster.signature.tokens.slice(0, 12).join(' ')
  const truncated = cluster.signature.tokens.length > 12 ? ` _(+${cluster.signature.tokens.length - 12} more)_` : ''

  const lines: string[] = []
  lines.push(`### ${human_label}`)
  lines.push('')
  lines.push(`- **id:** \`${cluster.cluster_id}\``)
  lines.push(`- **occurrences:** ${memberCount}`)
  if (suggested_role) lines.push(`- **role:** ${suggested_role}`)
  if (typeof confidence === 'number') {
    lines.push(`- **confidence:** ${confidence.toFixed(2)}`)
  }
  lines.push(`- **source:** ${source}`)
  lines.push(`- **tokens:** \`${tokenPreview}\`${truncated}`)
  lines.push('- **samples:**')
  for (const s of samples) {
    lines.push(`  - ${formatSampleLine(s.file, s.line)}`)
  }
  lines.push('')
  return lines.join('\n')
}

function groupByKind(clusters: LabeledCluster[]): Map<string, LabeledCluster[]> {
  const groups = new Map<string, LabeledCluster[]>()
  for (const lc of clusters) {
    const kind = lc.cluster.signature.kind
    const arr = groups.get(kind) ?? []
    arr.push(lc)
    groups.set(kind, arr)
  }
  for (const arr of groups.values()) {
    arr.sort((a, b) => b.cluster.members.length - a.cluster.members.length)
  }
  return groups
}

function metadataBlock(meta: ScanRunMetadata, total: number): string {
  return [
    '## Scan metadata',
    '',
    `- **schema:** v${meta.schema_version}`,
    `- **adapter:** ${meta.adapter}`,
    `- **scanned at:** ${meta.scanned_at}`,
    `- **project:** \`${meta.project_root}\``,
    `- **files scanned:** ${meta.files_scanned}`,
    `- **scan duration:** ${meta.duration_ms} ms`,
    `- **clusters:** ${total}`,
    '',
  ].join('\n')
}

function summaryBlock(groups: Map<string, LabeledCluster[]>): string {
  const lines: string[] = ['## Summary', '']
  lines.push('| Kind | Clusters | Top label |')
  lines.push('|------|----------|-----------|')
  const sortedKinds = Array.from(groups.keys()).sort((a, b) => {
    const an = groups.get(a)?.length ?? 0
    const bn = groups.get(b)?.length ?? 0
    return bn - an
  })
  for (const kind of sortedKinds) {
    const arr = groups.get(kind) ?? []
    const header = KIND_HEADERS[kind] ?? kind
    const top = arr[0]?.human_label ?? '—'
    lines.push(`| ${header} | ${arr.length} | \`${top}\` |`)
  }
  lines.push('')
  return lines.join('\n')
}

export function serializeCohereDesign(clusters: LabeledCluster[], options: SerializeOptions): string {
  const samplesPerCluster = options.samplesPerCluster ?? 3
  const groups = groupByKind(clusters)

  const sections: string[] = [
    '# Coherent Design (DRAFT)',
    '',
    DRAFT_BANNER,
    '',
    metadataBlock(options.metadata, clusters.length),
    summaryBlock(groups),
  ]

  const orderedKinds = Array.from(groups.keys()).sort((a, b) => {
    const an = groups.get(a)?.length ?? 0
    const bn = groups.get(b)?.length ?? 0
    return bn - an
  })

  for (const kind of orderedKinds) {
    const arr = groups.get(kind) ?? []
    sections.push(`## ${KIND_HEADERS[kind] ?? kind}`)
    sections.push('')
    for (const lc of arr) {
      sections.push(formatCluster(lc, samplesPerCluster))
    }
  }

  return (
    sections
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n'
  )
}
