/**
 * E3 token-artifact generator — one normalized token model (the project's
 * `design-system.config.ts` `tokens`) → three framework-ready outputs:
 *
 *   - design-tokens.json — the canonical model, machine-readable.
 *   - css-variables.css  — framework-agnostic `:root` / `.dark` custom props.
 *   - tailwind-v4.css     — the Tailwind v4 `@theme inline` + variables.
 *
 * All three are DERIVED from the same `config.tokens`, so they cannot drift
 * without one generator changing — `equivalence.ts` locks that as a CI gate.
 * This is the public promotion of the internal gallery generator (E3/T5).
 */

import type { DesignSystemConfig } from '@getcoherent/core'
import { buildCssVariables } from '@getcoherent/core'
import { generateV4GlobalsCss } from '../utils/tailwind-version.js'

export const DESIGN_TOKENS_VERSION = '1'

export type TokenFormat = 'json' | 'css' | 'tailwind'

export const TOKEN_FORMATS: TokenFormat[] = ['json', 'css', 'tailwind']

export const ARTIFACT_FILENAMES: Record<TokenFormat, string> = {
  json: 'design-tokens.json',
  css: 'css-variables.css',
  tailwind: 'tailwind-v4.css',
}

/** The canonical, machine-readable token model — the single source of truth. */
export function buildDesignTokensJson(config: DesignSystemConfig): string {
  const model = {
    $schema: 'https://getcoherent.design/schema/design-tokens-v1.json',
    version: DESIGN_TOKENS_VERSION,
    name: config.name ?? 'Design System',
    colors: config.tokens.colors, // { light, dark }
    typography: config.tokens.typography,
    spacing: config.tokens.spacing,
    radius: config.tokens.radius,
  }
  return JSON.stringify(model, null, 2) + '\n'
}

/** Framework-agnostic `:root` / `.dark` CSS custom properties. */
export function buildCssVariablesFile(config: DesignSystemConfig): string {
  return `/* Design tokens as CSS custom properties.\n * Generated by \`coherent export tokens\`. Do not edit by hand.\n */\n${buildCssVariables(config)}\n`
}

/** Tailwind v4 globals: \`@import "tailwindcss"\` + \`@theme inline\` + variables. */
export function buildTailwindV4File(config: DesignSystemConfig): string {
  return generateV4GlobalsCss(config)
}

/** Produce the { filename, content } for one format. */
export function buildArtifact(format: TokenFormat, config: DesignSystemConfig): { filename: string; content: string } {
  const filename = ARTIFACT_FILENAMES[format]
  switch (format) {
    case 'json':
      return { filename, content: buildDesignTokensJson(config) }
    case 'css':
      return { filename, content: buildCssVariablesFile(config) }
    case 'tailwind':
      return { filename, content: buildTailwindV4File(config) }
  }
}
