import type { DesignSystemConfig, ColorToken } from '@getcoherent/core'
import type { SharedComponentsManifest } from '@getcoherent/core'
import type { Atmosphere } from '../commands/chat/plan-generator.js'

const DESIGN_MD_VERSION = '1'

/**
 * Build a human-readable DESIGN.md summary of a generated project's design
 * system. Output goes alongside the code in the user's project root so:
 *  - a dev opening the repo months later can grasp the system without reading
 *    coherent.config.ts + globals.css + components.json separately
 *  - the file is portable: paste it into any AI tool as a design seed
 *  - GitHub renders it as the project's design contract page
 *
 * Pure function. No IO. Deterministic for a given input — safe to snapshot-test.
 *
 * Sections that have no data are omitted entirely (no empty stubs).
 */
export function buildDesignMarkdown(input: {
  config: DesignSystemConfig
  manifest?: SharedComponentsManifest
  atmosphere?: Atmosphere
}): string {
  const { config, manifest, atmosphere } = input
  const lines: string[] = []

  lines.push(`# ${config.name || 'Project'} — Design System`)
  lines.push('')
  if (config.description) {
    lines.push(config.description)
    lines.push('')
  }
  lines.push(
    `> Generated by [Coherent Design Method](https://getcoherent.design)${
      config.coherentVersion ? ` v${config.coherentVersion}` : ''
    }. Regenerate with \`coherent design-md\`.`,
  )
  lines.push('')

  if (atmosphere) {
    lines.push('## Atmosphere')
    lines.push('')
    if (atmosphere.moodPhrase) {
      lines.push(`**${atmosphere.moodPhrase}**`)
      lines.push('')
    }
    const rows: Array<[string, string]> = [
      ['Background', atmosphere.background],
      ['Hero layout', atmosphere.heroLayout],
      ['Spacing rhythm', atmosphere.spacing],
      ['Accents', atmosphere.accents],
      ['Font style', atmosphere.fontStyle],
    ]
    if (atmosphere.primaryHint) rows.push(['Primary hint', atmosphere.primaryHint])
    lines.push('| Aspect | Value |')
    lines.push('|--------|-------|')
    for (const [k, v] of rows) lines.push(`| ${k} | \`${v}\` |`)
    lines.push('')
  }

  lines.push('## Color System')
  lines.push('')
  lines.push(`Default mode: \`${config.theme.defaultMode}\`${config.theme.allowModeToggle ? ' (toggle enabled)' : ''}`)
  lines.push('')
  const colorRows = renderColorRows(config.tokens.colors.light, config.tokens.colors.dark)
  if (colorRows.length > 0) {
    lines.push('| Token | Light | Dark |')
    lines.push('|-------|-------|------|')
    lines.push(...colorRows)
    lines.push('')
  }

  if (config.tokenUsage?.colors && Object.keys(config.tokenUsage.colors).length > 0) {
    lines.push('### Color usage notes')
    lines.push('')
    for (const [token, hint] of Object.entries(config.tokenUsage.colors)) {
      lines.push(`- **${token}** — ${hint}`)
    }
    lines.push('')
  }

  lines.push('## Typography')
  lines.push('')
  const typo = config.tokens.typography
  if (typo.fontFamily) {
    lines.push('**Font families**')
    lines.push('')
    for (const [role, family] of Object.entries(typo.fontFamily)) {
      if (typeof family === 'string' && family.length > 0) {
        lines.push(`- **${role}** — ${family}`)
      }
    }
    lines.push('')
  }
  if (typo.fontSize) {
    lines.push('**Scale**')
    lines.push('')
    lines.push('| Step | Size |')
    lines.push('|------|------|')
    for (const [step, size] of Object.entries(typo.fontSize)) {
      if (typeof size === 'string') lines.push(`| ${step} | \`${size}\` |`)
    }
    lines.push('')
  }
  if (typo.lineHeight) {
    lines.push(
      '**Line heights** — ' +
        Object.entries(typo.lineHeight)
          .map(([k, v]) => `${k}: \`${v}\``)
          .join(', '),
    )
    lines.push('')
  }

  lines.push('## Spacing')
  lines.push('')
  const spacing = config.tokens.spacing
  if (spacing) {
    lines.push('| Token | Value |')
    lines.push('|-------|-------|')
    for (const [k, v] of Object.entries(spacing)) {
      if (typeof v === 'string') lines.push(`| ${k} | \`${v}\` |`)
    }
    lines.push('')
  }

  lines.push('## Border Radius')
  lines.push('')
  if (config.tokens.radius) {
    lines.push('| Token | Value |')
    lines.push('|-------|-------|')
    for (const [k, v] of Object.entries(config.tokens.radius)) {
      lines.push(`| ${k} | \`${v}\` |`)
    }
    lines.push('')
  }

  if (config.voice) {
    lines.push('## Voice')
    lines.push('')
    if (config.voice.tone) {
      lines.push(`**Tone** — ${config.voice.tone}`)
      lines.push('')
    }
    if (config.voice.copyRules && config.voice.copyRules.length > 0) {
      lines.push('**Copy rules**')
      lines.push('')
      for (const r of config.voice.copyRules) lines.push(`- ${r}`)
      lines.push('')
    }
    if (config.voice.avoidWords && config.voice.avoidWords.length > 0) {
      lines.push('**Avoid words** — ' + config.voice.avoidWords.map(w => `\`${w}\``).join(', '))
      lines.push('')
    }
    if (config.voice.ctaStyle) {
      lines.push(`**CTA style** — ${config.voice.ctaStyle}`)
      lines.push('')
    }
    if (config.voice.transparencyRules && config.voice.transparencyRules.length > 0) {
      lines.push('**Transparency rules**')
      lines.push('')
      for (const r of config.voice.transparencyRules) lines.push(`- ${r}`)
      lines.push('')
    }
  }

  if (manifest && manifest.shared.length > 0) {
    lines.push('## Shared Components')
    lines.push('')
    lines.push(
      'Reusable components extracted across pages. Reference any of these in CLI prompts as `@<id>` or `@<name>`:',
    )
    lines.push('')
    lines.push('| ID | Name | Type | Description |')
    lines.push('|----|------|------|-------------|')
    for (const c of manifest.shared) {
      const desc = (c.description || '').replace(/\|/g, '\\|').slice(0, 120)
      lines.push(`| \`${c.id}\` | **${c.name}** | ${c.type} | ${desc || '—'} |`)
    }
    lines.push('')
  }

  if (config.pages && config.pages.length > 0) {
    lines.push('## Pages')
    lines.push('')
    lines.push('| Route | Name | Description |')
    lines.push('|-------|------|-------------|')
    for (const p of config.pages) {
      const desc = (p.description || '').replace(/\|/g, '\\|').slice(0, 100)
      lines.push(`| \`${p.route}\` | ${p.name} | ${desc || '—'} |`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push(
    `<sub>DESIGN.md format v${DESIGN_MD_VERSION} • derived from \`coherent.config.ts\` + \`coherent.components.json\` • do not edit by hand — re-run \`coherent chat\` or \`coherent design-md\`.</sub>`,
  )
  lines.push('')

  return lines.join('\n')
}

function renderColorRows(light: ColorToken, dark: ColorToken): string[] {
  const rows: string[] = []
  const allKeys = new Set<string>([...Object.keys(light), ...Object.keys(dark)])
  const orderedKeys = [
    'background',
    'foreground',
    'primary',
    'primaryForeground',
    'secondary',
    'secondaryForeground',
    'muted',
    'mutedForeground',
    'accent',
    'accentForeground',
    'destructive',
    'destructiveForeground',
    'border',
    'input',
    'ring',
    'card',
    'cardForeground',
    'popover',
    'popoverForeground',
  ]
  const seen = new Set<string>()
  for (const k of orderedKeys) {
    if (!allKeys.has(k)) continue
    seen.add(k)
    rows.push(formatColorRow(k, light, dark))
  }
  for (const k of allKeys) {
    if (seen.has(k)) continue
    rows.push(formatColorRow(k, light, dark))
  }
  return rows
}

function formatColorRow(key: string, light: ColorToken, dark: ColorToken): string {
  const l = (light as Record<string, string>)[key] || ''
  const d = (dark as Record<string, string>)[key] || ''
  return `| \`${key}\` | ${l ? `\`${l}\`` : '—'} | ${d ? `\`${d}\`` : '—'} |`
}

export const DESIGN_MD_FILENAME = 'DESIGN.md'
