import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { existsSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import type { DesignSystemConfig, SharedComponentsManifest } from '@getcoherent/core'
import {
  buildProjectContext,
  formatForCursor,
  formatForClaude,
  formatForAgents,
  writeAllHarnessFiles,
  regenerateAllHarnessFiles,
} from './harness-context.js'
import { findConfig } from './find-config.js'

vi.mock('./find-config.js', () => ({
  findConfig: vi.fn(),
}))

const TEST_MANIFEST: SharedComponentsManifest = {
  shared: [
    {
      id: 'CID-001',
      name: 'Header',
      type: 'layout',
      file: 'components/shared/header.tsx',
      description: 'Site header with navigation',
      propsInterface: '{ logoUrl?: string }',
      usageExample: '<Header logoUrl="/logo.svg" />',
      usedIn: ['app/layout.tsx'],
      dependencies: [],
    },
    {
      id: 'CID-002',
      name: 'ActivityFeed',
      type: 'data-display',
      file: 'components/shared/activity-feed.tsx',
      description: 'Recent activity timeline',
      usedIn: ['app/(app)/dashboard/page.tsx', 'app/(app)/activity/page.tsx'],
      dependencies: [],
    },
  ],
  nextId: 3,
}

const TEST_CONFIG = {
  tokens: {
    colors: {
      light: {
        primary: 'oklch(0.637 0.237 25.331)',
        background: 'oklch(1 0 0)',
        foreground: 'oklch(0.145 0 0)',
        muted: 'oklch(0.97 0 0)',
        border: 'oklch(0.922 0 0)',
      },
      dark: {},
    },
    spacing: {},
    radius: { md: '0.5rem' },
  },
  pages: [],
  name: 'Test Project',
} as unknown as DesignSystemConfig

describe('buildProjectContext', () => {
  it('produces all required fields', () => {
    const ctx = buildProjectContext(TEST_MANIFEST, TEST_CONFIG)
    expect(ctx.sharedComponents).toContain('CID-001 Header')
    expect(ctx.sharedComponents).toContain('Import: import { Header }')
    expect(ctx.sharedComponentsCompact).toContain('CID-001 Header (layout)')
    expect(ctx.sharedComponentsCompact).not.toContain('Import:')
    expect(ctx.designTokens).toContain('Primary')
    expect(ctx.architectureDetailed).toContain('### Key directories')
    expect(ctx.architectureDetailed).toContain('### Config files')
    expect(ctx.architectureCompact).toContain('app/ —')
    expect(ctx.architectureCompact).not.toContain('### Key directories')
    expect(ctx.rulesDetailed).toContain('## Component Rules (MANDATORY)')
    expect(ctx.rulesDetailed).toContain('### Animation')
    expect(ctx.rulesCompact).toContain('ONLY use @/components/ui/*')
    expect(ctx.rulesCompact).not.toContain('## Component Rules (MANDATORY)')
    expect(ctx.designQuality).toContain('Design Quality Standards')
    expect(ctx.forms).toContain('Form Layout Rules')
    expect(ctx.accessibility).toContain('WCAG 2.2 AA')
    expect(ctx.auth).toContain('Auth Pages')
    expect(ctx.commands).toContain('coherent check')
    expect(ctx.platform).toContain('DO NOT')
  })

  it('handles empty manifest', () => {
    const ctx = buildProjectContext({ shared: [], nextId: 1 }, null)
    expect(ctx.sharedComponents).toContain('No shared components')
    expect(ctx.sharedComponentsCompact).toContain('No shared components')
    expect(ctx.designTokens).toContain('semantic')
  })
})

describe('formatForCursor', () => {
  it('matches snapshot for TEST_MANIFEST + TEST_CONFIG', () => {
    expect(formatForCursor(buildProjectContext(TEST_MANIFEST, TEST_CONFIG))).toMatchSnapshot()
  })
})

describe('formatForClaude', () => {
  it('includes compact components, compact rules, and design tokens', () => {
    const ctx = buildProjectContext(TEST_MANIFEST, TEST_CONFIG)
    const output = formatForClaude(ctx)
    expect(output).toContain('# Coherent Design Method Project')
    expect(output).toContain('CID-001 Header (layout)')
    expect(output).not.toContain('Import: import { Header }')
    expect(output).toContain('Primary')
    expect(output).toContain('ONLY use @/components/ui/*')
    expect(output).not.toContain('## Component Rules (MANDATORY)')
  })

  it('stays under 150 lines with test fixture', () => {
    const ctx = buildProjectContext(TEST_MANIFEST, TEST_CONFIG)
    const output = formatForClaude(ctx)
    const lineCount = output.split('\n').length
    expect(lineCount).toBeLessThan(150)
  })
})

describe('formatForAgents', () => {
  it('includes detailed rules, full components, neutral header', () => {
    const ctx = buildProjectContext(TEST_MANIFEST, TEST_CONFIG)
    const output = formatForAgents(ctx)
    expect(output).toContain('# Project Conventions')
    expect(output).toContain('Auto-generated by Coherent')
    expect(output).toContain('Import: import { Header }')
    expect(output).toContain('## Component Rules (MANDATORY)')
    expect(output).toContain('Primary')
  })

  it('does not reference Cursor or Claude Code', () => {
    const ctx = buildProjectContext(TEST_MANIFEST, TEST_CONFIG)
    const output = formatForAgents(ctx)
    expect(output.toLowerCase()).not.toContain('cursor')
    expect(output.toLowerCase()).not.toContain('claude')
  })
})

describe('writeAllHarnessFiles', () => {
  let tempDir: string

  beforeEach(() => {
    tempDir = join(tmpdir(), 'coherent-harness-test-' + Date.now())
    mkdirSync(tempDir, { recursive: true })
    // Create minimal coherent.components.json
    writeFileSync(join(tempDir, 'coherent.components.json'), JSON.stringify({ shared: [], nextId: 1 }))
  })

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true })
  })

  it('writes .cursorrules, CLAUDE.md, AGENTS.md', async () => {
    const result = await writeAllHarnessFiles(tempDir)
    expect(result.written).toBe(true)
    expect(existsSync(join(tempDir, '.cursorrules'))).toBe(true)
    expect(existsSync(join(tempDir, 'CLAUDE.md'))).toBe(true)
    expect(existsSync(join(tempDir, 'AGENTS.md'))).toBe(true)
  })

  it('writes .claude/* static files', async () => {
    await writeAllHarnessFiles(tempDir)
    expect(existsSync(join(tempDir, '.claude', 'commands', 'check.md'))).toBe(true)
    expect(existsSync(join(tempDir, '.claude', 'commands', 'fix.md'))).toBe(true)
    expect(existsSync(join(tempDir, '.claude', 'skills', 'coherent-chat', 'SKILL.md'))).toBe(true)
    expect(existsSync(join(tempDir, '.claude', 'settings.json'))).toBe(true)
  })

  it('returns correct counts', async () => {
    const result = await writeAllHarnessFiles(tempDir)
    expect(result.sharedCount).toBe(0)
    expect(result.tokenKeys).toBeUndefined()
  })
})

describe('regenerateAllHarnessFiles', () => {
  it('returns { written: false } when not in a Coherent project', async () => {
    vi.mocked(findConfig).mockReturnValueOnce(null)
    const result = await regenerateAllHarnessFiles()
    expect(result.written).toBe(false)
  })
})
