/**
 * Generation outcome record — one YAML per `coherent chat` invocation.
 *
 * Writes to `.coherent/runs/<timestamp>.yaml`. Enables "did memory help?"
 * analysis over time: compare runs with/without atmosphere overrides,
 * identify which kinds of intents succeed, track duration + error rate.
 *
 * Design choices:
 *  - One file per run (no append, no merge) — avoids locking + lets users
 *    delete one without touching others. Matches `.coherent/fix-sessions/` convention.
 *  - Raw YAML by hand (no `yaml` dependency) — keeps the CLI tree slim.
 *    Matches `packages/cli/src/commands/fix.ts` journaling style.
 *  - v1 captures what's cheap: timestamp, options, atmosphere, outcome, duration.
 *    Future enrichment (validator outcomes, wiki retrieval hits, user accept/reject)
 *    is additive — consumers of the YAML should tolerate missing fields.
 */

import { mkdirSync, writeFileSync } from 'fs'
import { resolve, relative } from 'path'

export interface RunRecordOptions {
  atmosphere?: string | null
  atmosphereOverride?: boolean
  page?: string | null
  component?: string | null
  newComponent?: string | null
  dryRun?: boolean
  interactive?: boolean
}

export interface RunRecordAtmosphere {
  background: string
  heroLayout: string
  spacing: string
  accents: string
  fontStyle: string
  primaryHint: string
  moodPhrase?: string
}

export interface RunRecord {
  /** ISO 8601 timestamp at run start. */
  timestamp: string
  /** Value of `@getcoherent/cli` version at runtime. */
  coherentVersion: string
  /** The user-supplied message / intent passed to `coherent chat`. */
  intent: string
  /** Options flags the user passed (only fields present are written). */
  options: RunRecordOptions
  /** Final `plan.atmosphere` after merge or preset override. Null when no plan. */
  atmosphere: RunRecordAtmosphere | null
  /** Paths (relative to project root) of TSX page files written during this run. */
  pagesWritten: string[]
  /** Paths (relative to project root) of shared component TSX files written. */
  sharedComponentsWritten: string[]
  /** Milliseconds from chat command entry to finally-block. */
  durationMs: number
  /** How the run exited. */
  outcome: 'success' | 'error' | 'aborted'
  /** Error message for `outcome: error` runs. Omit otherwise. */
  error?: string
}

const yamlEscape = (s: string) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`

const renderOptions = (opts: RunRecordOptions): string[] => {
  const lines: string[] = []
  lines.push('options:')
  if (opts.atmosphere != null) lines.push(`  atmosphere: ${yamlEscape(opts.atmosphere)}`)
  else lines.push('  atmosphere: null')
  if (typeof opts.atmosphereOverride === 'boolean') lines.push(`  atmosphereOverride: ${opts.atmosphereOverride}`)
  if (opts.page) lines.push(`  page: ${yamlEscape(opts.page)}`)
  if (opts.component) lines.push(`  component: ${yamlEscape(opts.component)}`)
  if (opts.newComponent) lines.push(`  newComponent: ${yamlEscape(opts.newComponent)}`)
  if (opts.dryRun) lines.push(`  dryRun: true`)
  if (opts.interactive) lines.push(`  interactive: true`)
  return lines
}

const renderAtmosphere = (a: RunRecordAtmosphere | null): string[] => {
  if (a == null) return ['atmosphere: null']
  const lines = ['atmosphere:']
  lines.push(`  background: ${yamlEscape(a.background)}`)
  lines.push(`  heroLayout: ${yamlEscape(a.heroLayout)}`)
  lines.push(`  spacing: ${yamlEscape(a.spacing)}`)
  lines.push(`  accents: ${yamlEscape(a.accents)}`)
  lines.push(`  fontStyle: ${yamlEscape(a.fontStyle)}`)
  lines.push(`  primaryHint: ${yamlEscape(a.primaryHint)}`)
  if (a.moodPhrase) lines.push(`  moodPhrase: ${yamlEscape(a.moodPhrase)}`)
  return lines
}

const renderList = (header: string, items: string[]): string[] => {
  if (items.length === 0) return [`${header}: []`]
  return [`${header}:`, ...items.map(item => `  - ${yamlEscape(item)}`)]
}

export function renderRunRecordYaml(record: RunRecord): string {
  const lines: string[] = [
    '# coherent chat run — generation outcome record',
    '# Generated by `coherent chat`. One file per invocation. Do not edit by hand.',
    `timestamp: ${record.timestamp}`,
    `coherentVersion: ${yamlEscape(record.coherentVersion)}`,
    `intent: ${yamlEscape(record.intent)}`,
    ...renderOptions(record.options),
    ...renderAtmosphere(record.atmosphere),
    ...renderList('pagesWritten', record.pagesWritten),
    ...renderList('sharedComponentsWritten', record.sharedComponentsWritten),
    `durationMs: ${record.durationMs}`,
    `outcome: ${record.outcome}`,
  ]
  if (record.error) lines.push(`error: ${yamlEscape(record.error)}`)
  lines.push('')
  return lines.join('\n')
}

function timestampFilename(isoTimestamp: string): string {
  return isoTimestamp.replace(/[:.]/g, '-').replace(/-\d{3}Z$/, 'Z')
}

/**
 * Write the run record to `.coherent/runs/<timestamp>.yaml` under `projectRoot`.
 * Creates the directory if missing. Returns the absolute path of the written file.
 * Never throws on filesystem errors — caller can ignore the return value when
 * failure to journal is acceptable (most chat invocations).
 */
export function writeRunRecord(projectRoot: string, record: RunRecord): string | null {
  try {
    const dir = resolve(projectRoot, '.coherent', 'runs')
    mkdirSync(dir, { recursive: true })
    const path = resolve(dir, `${timestampFilename(record.timestamp)}.yaml`)
    writeFileSync(path, renderRunRecordYaml(record), 'utf-8')
    return path
  } catch {
    return null
  }
}

/**
 * Relative-path convenience — returns the `.coherent/runs/<file>` form
 * (useful for printing to users without leaking absolute paths).
 */
export function writeRunRecordRel(projectRoot: string, record: RunRecord): string | null {
  const abs = writeRunRecord(projectRoot, record)
  return abs ? relative(projectRoot, abs) : null
}
