import { describe, it, expect } from 'vitest'
import { extractConfigObject, DesignSystemManager } from './DesignSystemManager.js'
import { EXAMPLE_MULTIPAGE_CONFIG } from '../types/design-system.js'
import { writeFileSync, mkdirSync, rmSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'

describe('extractConfigObject', () => {
  it('extracts simple JSON object', () => {
    const source = 'export const config = {"name": "test"}'
    expect(extractConfigObject(source)).toBe('{"name": "test"}')
  })

  it('extracts nested objects', () => {
    const source = `export const config = {
  "name": "test",
  "tokens": {
    "colors": {
      "primary": "#000"
    }
  }
}`
    const result = JSON.parse(extractConfigObject(source))
    expect(result.name).toBe('test')
    expect(result.tokens.colors.primary).toBe('#000')
  })

  it('handles "as const" suffix', () => {
    const source = `export const config = {"name": "test"} as const`
    expect(extractConfigObject(source)).toBe('{"name": "test"}')
  })

  it('handles type annotation before equals', () => {
    const source = `export const config: DesignSystemConfig = {"name": "typed"}`
    expect(extractConfigObject(source)).toBe('{"name": "typed"}')
  })

  it('handles strings with braces inside', () => {
    const source = `export const config = {"description": "use { and } in text"}`
    const result = JSON.parse(extractConfigObject(source))
    expect(result.description).toBe('use { and } in text')
  })

  it('handles escaped quotes in strings', () => {
    const source = `export const config = {"value": "say \\"hello\\""}`
    const result = JSON.parse(extractConfigObject(source))
    expect(result.value).toBe('say "hello"')
  })

  it('ignores content after the config object', () => {
    const source = `export const config = {"name": "test"} as const

// some trailing comment
export function other() { return 42 }
`
    expect(extractConfigObject(source)).toBe('{"name": "test"}')
  })

  it('ignores content before the config export', () => {
    const source = `/**
 * Design System Configuration
 */
import { DesignSystemConfig } from './types'

export const config = {"name": "test"}
`
    expect(extractConfigObject(source)).toBe('{"name": "test"}')
  })

  it('throws on missing config export', () => {
    const source = 'export const other = {"name": "test"}'
    expect(() => extractConfigObject(source)).toThrow('Invalid config file format')
  })

  it('throws on missing opening brace', () => {
    const source = 'export const config = "not an object"'
    expect(() => extractConfigObject(source)).toThrow('no opening brace')
  })

  it('throws on unbalanced braces', () => {
    const source = 'export const config = {"name": "test"'
    expect(() => extractConfigObject(source)).toThrow('unbalanced braces')
  })

  it('handles real-world multiline config', () => {
    const source = `/**
 * Design System Configuration
 * Auto-generated by Coherent Design Method.
 */

export const config = {
  "name": "My App",
  "description": "A design system",
  "version": "1.0.0",
  "createdAt": "2026-01-01T00:00:00.000Z",
  "updatedAt": "2026-03-16T00:00:00.000Z",
  "tokens": {
    "colors": {
      "light": {
        "primary": "hsl(222.2 47.4% 11.2%)",
        "secondary": "hsl(210 40% 96.1%)"
      }
    }
  },
  "components": [],
  "pages": []
} as const
`
    const result = JSON.parse(extractConfigObject(source))
    expect(result.name).toBe('My App')
    expect(result.tokens.colors.light.primary).toBe('hsl(222.2 47.4% 11.2%)')
    expect(result.components).toEqual([])
  })
})

function createTestDSM(): { dsm: DesignSystemManager; cleanup: () => void } {
  const dir = join(tmpdir(), `dsm-test-${Date.now()}-${Math.random().toString(36).slice(2)}`)
  mkdirSync(dir, { recursive: true })
  const configPath = join(dir, 'design-system.config.ts')
  writeFileSync(configPath, `export const config = ${JSON.stringify(EXAMPLE_MULTIPAGE_CONFIG)} as const`)
  const dsm = new DesignSystemManager(configPath)
  return { dsm, cleanup: () => rmSync(dir, { recursive: true, force: true }) }
}

describe('DesignSystemManager.updateToken — path validation', () => {
  it('rejects unknown color fields', async () => {
    const { dsm, cleanup } = createTestDSM()
    await dsm.load()
    const result = await dsm.updateToken('colors.light.indigo', '#4F46E5')
    expect(result.success).toBe(false)
    expect(result.message).toContain('Invalid token path')
    cleanup()
  })

  it('allows valid color paths', async () => {
    const { dsm, cleanup } = createTestDSM()
    await dsm.load()
    const result = await dsm.updateToken('colors.light.primary', '#4F46E5')
    expect(result.success).toBe(true)
    cleanup()
  })

  it('allows valid spacing paths', async () => {
    const { dsm, cleanup } = createTestDSM()
    await dsm.load()
    const result = await dsm.updateToken('spacing.md', '1.5rem')
    expect(result.success).toBe(true)
    cleanup()
  })
})

describe('DesignSystemManager.updateToken — error formatting', () => {
  it('shows human-readable error for invalid hex', async () => {
    const { dsm, cleanup } = createTestDSM()
    await dsm.load()
    const result = await dsm.updateToken('colors.light.primary', 'not-hex')
    expect(result.success).toBe(false)
    expect(result.message).not.toContain('"validation"')
    expect(result.message).not.toContain('"code"')
    expect(result.message).toContain('Must be valid hex color')
    cleanup()
  })
})

describe('DesignSystemManager.updateToken — no-op', () => {
  it('skips no-op when value unchanged', async () => {
    const { dsm, cleanup } = createTestDSM()
    await dsm.load()
    const result = await dsm.updateToken('colors.light.primary', dsm.getConfig().tokens.colors.light.primary)
    expect(result.success).toBe(true)
    expect(result.modified).toEqual([])
    expect(result.message).toContain('already set')
    cleanup()
  })
})
