/**
 * Design System Manager
 *
 * Main orchestrator for design system operations.
 * All modifications flow through this class.
 */

import type {
  DesignSystemConfig,
  ComponentDefinition,
  PageDefinition,
  ModificationResult,
  ComponentDependency,
} from '../types/design-system.js'
import { validateConfig, getComponent, componentExists } from '../types/design-system.js'
import { readFile } from 'fs/promises'
import { atomicWriteFile } from '../utils/atomicWrite.js'

export class DesignSystemManager {
  private config: DesignSystemConfig | null = null
  private configPath: string
  private componentRegistry: Map<string, ComponentDefinition> = new Map()

  constructor(configPath: string) {
    this.configPath = configPath
  }

  /**
   * Load config from file and validate
   */
  async load(): Promise<void> {
    try {
      const fileContent = await readFile(this.configPath, 'utf-8')

      const configJson = extractConfigObject(fileContent)
      const config = JSON.parse(configJson)

      // Validate with Zod
      this.config = validateConfig(config)

      // Load component registry
      this.loadComponentRegistry()
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`Failed to load config from ${this.configPath}: ${error.message}`)
      }
      throw error
    }
  }

  /**
   * Save config to file
   */
  async save(): Promise<void> {
    if (!this.config) {
      throw new Error('Config not loaded. Call load() first.')
    }

    try {
      const fileContent = `/**
 * Design System Configuration
 * 
 * This file is auto-generated by Coherent Design Method.
 * Do not edit manually - use 'coherent chat' command to modify.
 */

export const config = ${JSON.stringify(this.config, null, 2)} as const
`
      await atomicWriteFile(this.configPath, fileContent)
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`Failed to save config to ${this.configPath}: ${error.message}`)
      }
      throw error
    }
  }

  /**
   * Get current config
   */
  getConfig(): DesignSystemConfig {
    if (!this.config) {
      throw new Error('Config not loaded. Call load() first.')
    }
    return this.config
  }

  /**
   * Replace in-memory config (e.g. after ComponentManager or PageManager mutation)
   */
  updateConfig(newConfig: DesignSystemConfig): void {
    this.config = validateConfig(newConfig)
    this.loadComponentRegistry()
  }

  /**
   * Update design token and cascade to affected components
   */
  async updateToken(path: string, value: unknown): Promise<ModificationResult> {
    if (!this.config) {
      throw new Error('Config not loaded. Call load() first.')
    }

    try {
      // Update token in config
      const pathParts = path.split('.')
      let current: any = this.config.tokens

      for (let i = 0; i < pathParts.length - 1; i++) {
        const part = pathParts[i]
        if (!(part in current)) {
          throw new Error(`Invalid token path: ${path}`)
        }
        current = current[part]
      }

      const lastPart = pathParts[pathParts.length - 1]
      const oldValue = current[lastPart]
      current[lastPart] = value

      // Validate updated config
      this.config = validateConfig(this.config)

      // Find affected components (simplified - will be enhanced in Task 1.8)
      const affectedComponents: string[] = []
      const affectedPages: string[] = []

      // TODO: In Task 1.8, implement proper dependency tracking
      // For now, just mark that token was updated
      if (path.includes('primary') || path.includes('color')) {
        // Color changes affect many components
        this.config.components.forEach(comp => {
          if (comp.baseClassName.includes('primary') || comp.baseClassName.includes('bg-')) {
            affectedComponents.push(comp.id)
          }
        })
      }

      // Find pages using affected components
      this.config.pages.forEach(page => {
        page.sections.forEach(section => {
          if (affectedComponents.includes(section.componentId)) {
            affectedPages.push(page.id)
          }
        })
      })

      return {
        success: true,
        modified: [
          `token:${path}`,
          ...affectedComponents.map(id => `component:${id}`),
          ...affectedPages.map(id => `page:${id}`),
        ],
        config: this.config,
        message: `Updated token ${path} from ${oldValue} to ${value}`,
        warnings:
          affectedComponents.length > 0
            ? [`This change affects ${affectedComponents.length} components and ${affectedPages.length} pages`]
            : undefined,
      }
    } catch (error) {
      if (error instanceof Error) {
        return {
          success: false,
          modified: [],
          config: this.config,
          message: `Failed to update token: ${error.message}`,
        }
      }
      throw error
    }
  }

  /**
   * Add component to registry
   */
  async addComponent(def: ComponentDefinition): Promise<ModificationResult> {
    if (!this.config) {
      throw new Error('Config not loaded. Call load() first.')
    }

    try {
      // Check if component already exists
      if (componentExists(this.config, def.id)) {
        return {
          success: false,
          modified: [],
          config: this.config,
          message: `Component ${def.id} already exists. Use updateComponent() to modify it.`,
          warnings: ['Component reuse is recommended. Check if similar component exists.'],
        }
      }

      // Add to config
      this.config.components.push(def)
      this.config.updatedAt = new Date().toISOString()

      // Validate
      this.config = validateConfig(this.config)

      // Update registry
      this.componentRegistry.set(def.id, def)

      return {
        success: true,
        modified: [`component:${def.id}`],
        config: this.config,
        message: `Added component ${def.name} (${def.id})`,
      }
    } catch (error) {
      if (error instanceof Error) {
        return {
          success: false,
          modified: [],
          config: this.config,
          message: `Failed to add component: ${error.message}`,
        }
      }
      throw error
    }
  }

  /**
   * Add page to config
   */
  async addPage(def: PageDefinition): Promise<ModificationResult> {
    if (!this.config) {
      throw new Error('Config not loaded. Call load() first.')
    }

    try {
      // Check if page route already exists
      const existingPage = this.config.pages.find(p => p.route === def.route)
      if (existingPage) {
        return {
          success: false,
          modified: [],
          config: this.config,
          message: `Page with route ${def.route} already exists`,
        }
      }

      // Validate all component references exist
      const missingComponents: string[] = []
      def.sections.forEach(section => {
        if (!componentExists(this.config!, section.componentId)) {
          missingComponents.push(section.componentId)
        }
      })

      if (missingComponents.length > 0) {
        return {
          success: false,
          modified: [],
          config: this.config,
          message: `Missing components: ${missingComponents.join(', ')}`,
          warnings: ['Create components first before adding page'],
        }
      }

      // Add page
      this.config.pages.push(def)
      this.config.updatedAt = new Date().toISOString()

      // Update navigation if enabled
      if (this.config.navigation?.enabled) {
        if (!this.config.navigation.items.find(item => item.route === def.route)) {
          this.config.navigation.items.push({
            label: def.name,
            route: def.route,
            order: this.config.navigation.items.length + 1,
            requiresAuth: def.requiresAuth,
          })
          // Sort by order
          this.config.navigation.items.sort((a, b) => a.order - b.order)
        }
      }

      // Validate
      this.config = validateConfig(this.config)

      // Update component usage tracking
      def.sections.forEach(section => {
        const component = getComponent(this.config!, section.componentId)
        if (component && !component.usedInPages.includes(def.route)) {
          component.usedInPages.push(def.route)
        }
      })

      return {
        success: true,
        modified: [`page:${def.id}`],
        config: this.config,
        message: `Added page ${def.name} at ${def.route}`,
      }
    } catch (error) {
      if (error instanceof Error) {
        return {
          success: false,
          modified: [],
          config: this.config,
          message: `Failed to add page: ${error.message}`,
        }
      }
      throw error
    }
  }

  /**
   * Find component by ID
   */
  findComponent(id: string): ComponentDefinition | null {
    if (!this.config) {
      return null
    }
    return getComponent(this.config, id) || null
  }

  /**
   * Get component dependencies
   */
  getComponentDependencies(componentId: string): ComponentDependency {
    if (!this.config) {
      throw new Error('Config not loaded. Call load() first.')
    }

    const component = getComponent(this.config, componentId)
    if (!component) {
      throw new Error(`Component ${componentId} not found`)
    }

    const usedBy: string[] = []
    this.config.pages.forEach(page => {
      page.sections.forEach(section => {
        if (section.componentId === componentId) {
          usedBy.push(page.id)
        }
      })
    })

    return {
      componentId,
      dependsOn: [], // TODO: Implement in Task 1.8
      usedBy,
    }
  }

  /**
   * Get pages affected by component
   */
  getAffectedPages(componentId: string): string[] {
    if (!this.config) {
      return []
    }

    const pages: string[] = []
    this.config.pages.forEach(page => {
      page.sections.forEach(section => {
        if (section.componentId === componentId) {
          pages.push(page.id)
        }
      })
    })

    return pages
  }

  /**
   * Load component registry from config
   */
  private loadComponentRegistry(): void {
    if (!this.config) {
      return
    }

    this.componentRegistry.clear()
    this.config.components.forEach(comp => {
      this.componentRegistry.set(comp.id, comp)
    })
  }

  /**
   * Reload config from file
   */
  async reload(): Promise<void> {
    await this.load()
  }
}

/**
 * Extract the config object from a TypeScript source file using balanced-brace matching.
 * More robust than a greedy regex — correctly handles nested objects and trailing content.
 */
export function extractConfigObject(source: string): string {
  const marker = source.match(/export\s+const\s+config[^=]*=\s*/)
  if (!marker || marker.index === undefined) {
    throw new Error('Invalid config file format. Expected: export const config = { ... }')
  }

  const startSearch = marker.index + marker[0].length
  const openBrace = source.indexOf('{', startSearch)
  if (openBrace === -1) {
    throw new Error('Invalid config file format: no opening brace found after config =')
  }

  let depth = 0
  let inString = false
  let escape = false
  for (let i = openBrace; i < source.length; i++) {
    const ch = source[i]
    if (escape) {
      escape = false
      continue
    }
    if (ch === '\\' && inString) {
      escape = true
      continue
    }
    if (ch === '"' && !escape) {
      inString = !inString
      continue
    }
    if (inString) continue
    if (ch === '{') depth++
    else if (ch === '}') {
      depth--
      if (depth === 0) {
        return source.slice(openBrace, i + 1)
      }
    }
  }

  throw new Error('Invalid config file format: unbalanced braces')
}
